application: ebay-now
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  script: main.app
  
- url: /courier
  script: courierHandler.app

- url: /courier/\d+/complete
  script: courierHandler.app

- url: /courier/\d+/online
  script: courierHandler.app

- url: /courier/\d+/offline
  script: courierHandler.app

- url: /courier/\d+/accept/\d+
  script: courierHandler.app

- url: /order/new
  script: orderHandler.app

libraries:
- name: webapp2
  version: "2.5.1"
- name: jinja2
  version: latest
