application: ebay-now
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /stylesheets
  static_dir: stylesheets

- url: /
  script: main.app
  
- url: /courier/new
  script: courierHandler.app

- url: /courier/\d+/complete
  script: courierHandler.app

- url: /courier/\d+/online
  script: courierHandler.app

- url: /courier/\d+/offline
  script: courierHandler.app

- url: /courier/\d+/accept/\d+
  script: courierHandler.app

- url: /courier/online
  script: courierHandler.app

- url: /courier/offline
  script: courierHandler.app

- url: /courier
  script: courierHandler.app

- url: /order/new
  script: orderHandler.app

- url: /order/needPickup
  script: orderHandler.app

- url: /order/enRoute
  script: orderHandler.app

- url: /order/delivered
  script: orderHandler.app

libraries:
- name: webapp2
  version: "2.5.1"
- name: jinja2
  version: latest
